In [1]:
# installing torch 
%pip install torch

  Using cached torch-2.4.0-cp310-cp310-win_amd64.whl (197.9 MB)
  Using cached sympy-1.13.2-py3-none-any.whl (6.2 MB)
  Using cached fsspec-2024.6.1-py3-none-any.whl (177 kB)
  Using cached filelock-3.15.4-py3-none-any.whl (16 kB)
  Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
  Using cached networkx-3.3-py3-none-any.whl (1.7 MB)
  Using cached MarkupSafe-2.1.5-cp310-cp310-win_amd64.whl (17 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\Users\Owner\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [3]:
# opened the dataset & stored it in a text var
with open("input.txt", 'r', encoding='utf-8') as file:
    text = file.read()

text[:1000]


"First Citizen:\nBefore we proceed any further, hear me speak.\n\nAll:\nSpeak, speak.\n\nFirst Citizen:\nYou are all resolved rather to die than to famish?\n\nAll:\nResolved. resolved.\n\nFirst Citizen:\nFirst, you know Caius Marcius is chief enemy to the people.\n\nAll:\nWe know't, we know't.\n\nFirst Citizen:\nLet us kill him, and we'll have corn at our own price.\nIs't a verdict?\n\nAll:\nNo more talking on't; let it be done: away, away!\n\nSecond Citizen:\nOne word, good citizens.\n\nFirst Citizen:\nWe are accounted poor citizens, the patricians good.\nWhat authority surfeits on would relieve us: if they\nwould yield us but the superfluity, while it were\nwholesome, we might guess they relieved us humanely;\nbut they think we are too dear: the leanness that\nafflicts us, the object of our misery, is as an\ninventory to particularise their abundance; our\nsufferance is a gain to them Let us revenge this with\nour pikes, ere we become rakes: for the gods know I\nspeak this in hunger 

In [4]:
# Tokenization from a character level

# got the vocab/token size
vocab = sorted(list(set(text)))
vocab_size = len(vocab)
print(vocab)
print(vocab_size)

['\n', ' ', '!', '$', '&', "'", ',', '-', '.', '3', ':', ';', '?', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
65


In [5]:

# Preprocessing

# a list of vocab & int that map to each other with id
char_to_int = {chr:i for i, chr in enumerate(vocab)}
int_to_char = {i:chr for i, chr in enumerate(vocab)}

# a function that returns an int for a string of characters.
encode = lambda s: [char_to_int[c] for c in s]

# a function that joins the char equivalent of each int in a list & returns it. 
decode = lambda l: "".join(int_to_char[i] for i in l)

# testing above functions
print(encode("pavel"))
print(decode([0, 1, 2, 3, 4]))

[54, 39, 60, 43, 50]

 !$&


In [6]:
# Tensor Wrapping

import torch

# encoding our dataset of text
data = encode(text)

# wrapping our data in a tensor
data = torch.tensor(data, dtype=torch.long)

print(data[:1000])

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
        47, 59, 57,  1, 47, 57,  1, 41, 

In [10]:
# Train - Test Data Split

from sklearn.model_selection import train_test_split

# 80 - 20 split
n = int(0.8*len(data))

# 80% for training data
train = data[:n]
test = data[n:]

print(train[:100])
print(test[:100])


tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59])
tensor([63, 53, 59,  1, 39, 56, 43,  6,  0, 32, 46, 39, 58,  1, 47, 57,  6,  1,
        39,  1, 61, 53, 51, 39, 52, 11,  1, 47, 44,  1, 63, 53, 59,  1, 40, 43,
         1, 51, 53, 56, 43,  6,  1, 63, 53, 59,  5, 56, 43,  1, 52, 53, 52, 43,
        11,  0, 21, 44,  1, 63, 53, 59,  1, 40, 43,  1, 53, 52, 43,  6,  1, 39,
        57,  1, 63, 53, 59,  1, 39, 56, 43,  1, 61, 43, 50, 50,  1, 43, 62, 54,
        56, 43, 57, 57,  5, 42,  0, 14, 63,  1])
